In [1]:
%run ./start_up.ipynb

Spark version: 3.5.0
Spark UI: http://localhost:4040

In [2]:
from recommenders import train_item_item

trained_ii_model, score_history = train_item_item(anime_data)

In [3]:
from recommenders import get_similar_items_for_user
target_uid = final_data.select('user_id').first()[0]
get_similar_items_for_user(target_uid, final_data, trained_ii_model, score_history, 100)

      anime_id    avg_sim  final_score
551      11739  89.385356     1.000000
555      10943  89.385356     1.000000
554       5992  89.385356     1.000000
552      10460  89.385356     1.000000
1414     23447  89.262162     0.998514
...        ...        ...          ...
2921        53  80.152110     0.888645
2928       260  80.152110     0.888645
2926       394  80.152110     0.888645
2413     33581  79.962290     0.886355
754      36220  79.697846     0.883166

[100 rows x 3 columns]

In [4]:
def ii_model(user_id, n=10):
    return get_similar_items_for_user(user_id, final_data, trained_ii_model, score_history, n)

In [5]:
from recommenders import hybridV1
from pyspark.ml.recommendation import ALSModel
ui_model = ALSModel.load('/home/jovyan/work/models/user-item')

hybridV1(target_uid, ui_model, ii_model, final_data, score_history, spark, 10)

    anime_id   ui_score   ii_score  ui_score_norm  ii_score_norm  hybrid_score
91     38753  10.546517  81.369539       0.622808       1.000000     45.958028
79     35988  11.073065  68.382801       0.653107       0.840398     39.727933
72     33161  11.063675  67.318956       0.652567       0.827324     39.191315
30      3467  11.103932  65.792707       0.654883       0.808567     38.448320
26      2523  10.737107  65.239504       0.633775       0.801768     37.988306
42     10444  10.791490  64.772335       0.636905       0.796027     37.781913
82     36885  14.139758  60.018858       0.829572       0.737608     37.079308
71     32924  10.942916  62.774720       0.645618       0.771477     36.858818
88     37986  10.561589  61.815636       0.623676       0.759690     36.188613
32      3848  10.505328  60.715408       0.620438       0.746169     35.610368